# This file allows you to configure the Dart analyzer.
#
# The commented part below is just for inspiration. Read the guide here:
#   https://www.dartlang.org/guides/language/analysis-options
include: package:lints/recommended.yaml

analyzer:


linter:
  rules:
    prefer_final_fields: false